### PR TITLE
Clarify and fix `isRepoRoot`

### LINKED ISSUE #24: `isRepoRoot` Fails on https://github.com/Witold101/wpw
https://github.com/Witold101/wpw

I can't figure out why. Maybe because the username start with an upper case letter? but in this repo we are not doing `.toLowercase()`??

### PR DESCRIPTION
**Pull request by fregante**
Fixes #24 
Fixes https://github.com/sindresorhus/refined-github/issues/3393

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -293,9 +293,25 @@ collect.set('isRepoHome', [
...
+
+	if (url) {
+		// Root of a branch/commit/tag
+		return /^tree\/[^/]+$/.test(repoPath!);
+	}
+
+	// If we're checking the current page, add support for branches with slashes // #15 #24
+	const title = document.title.toLowerCase();
+	const repoURL = getRepoURL().toLowerCase();
+	return String(repoPath).startsWith('tree/') && title.startsWith(repoURL) && !title.endsWith(repoURL);
```
Comment (fregante) [inline index.ts:312]: After merging https://github.com/fregante/github-url-detection/pull/26, this can be simplified to
```suggestion
	const repoURL = getRepoURL();
	return String(repoPath).startsWith('tree/') && document.title.startsWith(repoURL) && !document.title.endsWith(repoURL);
```

**Comment by yakov116** [comment]
@fregante how can I test it? is there a way to link a this pull in the RH package.json? I get an error when trying.

**Comment by kidonng** [comment]
@yakov116 Try `npm i fregante/github-url-detection@is-repo-root`

**Comment by fregante** [comment]
I think so, but build it first

**Comment by kidonng** [comment]
😅 I forgot this is a TS project
